name: Deploy to Netlify on Tag Commit

on:
  push:
    tags:
      - 'v\d\.\d\.(\d{3}|\d{2}|\d{1})+(-rc-\d+)?'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (specify the version your project requires)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project (optional, if you want to build it before deploying)
      - name: Build the project
        run: npm run build  # Adjust this if you need to run a specific build command

      - name: Deploy to netlify
        run: curl -X POST -d {} ${{ secret.NETLIFY_BUILD_HOOK }}
